### ISSUE TITLE
Custom type annotation

### ISSUE THREAD

**Issue by anotheri** [m1212e/prismabox#29]
Now it's possible to redefine of existing default types as @m1212e shown in https://github.com/m1212e/prismabox/issues/25#issuecomment-2608428850.

But instead of overriding the default type mapping for _all the strings_ for example (or _all the dates_, whatever), i'd like to be able to define a new type with custom transformation and use it just for a couple of fields in Prisma schema and keep the default type mapping for other fields.

E.g. if i extend Type with new type:

```typescript
import { Type as NativeType } from "@sinclair/typebox";

// e.g. in DB it's stored as string | null but API returns it as integer
const StringifiedInt = NativeType.Transform(NativeType.Integer())
  .Decode((value) => (value === 0 ? null : toString(value)))
  .Encode((value) => parseInt(value || '0', 10));

export const Type = {
  ...NativeType,
  StringifiedInt,
};
```

and then i'd like to apply this new custom type to a Prisma schema field via annotation:

```Prisma
model myModel {
  /// @prismabox.type=StringifiedInt
  myCustomField String? @db.TinyText
}
```

It's supposed to be quite useful for BigInt type fields which are still not supported good enough in JSON and require transformation to string: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json

Thanks in advance!

**Comment by m1212e** [comment]
Hey, please see https://www.npmjs.com/package/prismabox/v/1.1.18-prerelease.0 

I released a version under the @dev tag which you can install via npm. Please see if this is what you need!

**Comment by anotheri** [comment]
@m1212e on my codebase, i've noticed an issue with applying `__nullable__` to `typeOverwrite`.

It's exactly the same `StringifiedInt` example i've mentioned above. So to clarify I'd expect that `__nullable__` to be applied to a type inside the `Transform` but not to a whole `StringifiedInt` type. Although it might be quite complicated case for codegen, so it's probably better to bypass wrapping into `__nullable__` for custom (overriten) types either as a default behaviour or optionally via another annotation (both options look good for me).

**Comment by anotheri** [comment]
@m1212e sure! Unfortunately, i had no time to take a look into that branch recently, but I'll try with latest version soon and share an example here if something still doesn't seem right. And thanks for your support!

**Comment by anotheri** [comment]
@m1212e sorry for long delay, i'll try to explain the problem with a bit more examples:

so considering the same example above:
```prisma
model myModel {
  /// @prismabox. typeOverwrite=StringifiedInt
  myCustomField String? @db.TinyText
}
```

it generates code like this:
```typescript
myCustomField: __nullable__(
  NativeType.Transform(NativeType.Integer())
    .Decode((value) => (value === 0 ? null : toString(value)))
    .Encode((value) => parseInt(value || '0', 10))
)
```

which equals to:
```typescript
Type.Union([
  NativeType.Transform(NativeType.Integer())
    .Decode((value) => (value === 0 ? null : toString(value)))
    .Encode((value) => parseInt(value || '0', 10))
  Type.Null()
]),
```

and i'd expect to have
```typescript
NativeType.Transform(
  Type.Union([
    Type.Null(),
    Type.Integer({}),
  ]),
)
  .Decode((value) => (value === 0 ? null : toString(value)))
  .Encode((value) => parseInt(value || '0', 10))
```

I assume that both scenarios might be helpful depending on the requirements, but now there is no way to configure the one i'd expected to get mixing custom type with nullable field.
